### ISSUE TITLE
Update the ingester to the new snappy format

### ISSUE THREAD

**Issue by FlorianLautenschlager** [ChronixDB/chronix.ingester#10]
We have to update the chronix.ingester to the latest snappy format:  prometheus/prometheus#2696

*Discuss:* Do we need backward compatibility?

**Comment by juliusv** [comment]
@FlorianLautenschlager Happy to do this if QAWare is interested.

> Discuss: Do we need backward compatibility?

I think this is up to you... Have you been using the ingester for real, and need to keep using it against old Prometheus installations? Do you know of external people using it?
