### ISSUE TITLE
Getting error while building chronix.ingester: [cannot find package "github.com/ChronixDB/chronix.go/chronix"]

### ISSUE THREAD

**Issue by Niranjs** [ChronixDB/chronix.ingester#13]
I'm getting the following error when I ran "go build" inside chronix.ingester directory.

:~/chronix/chronix-ingester/chronix.ingester$ go build
main.go:12:2: cannot find package "github.com/ChronixDB/chronix.go/chronix" in any of:
        /usr/local/go/src/github.com/ChronixDB/chronix.go/chronix (from $GOROOT)
        /home/ubuntu/chronix/chronix-ingester/src/github.com/ChronixDB/chronix.go/chronix (from $GOPATH)
main.go:13:2: cannot find package "github.com/ChronixDB/chronix.ingester/ingester" in any of:
        /usr/local/go/src/github.com/ChronixDB/chronix.ingester/ingester (from $GOROOT)
        /home/ubuntu/chronix/chronix-ingester/src/github.com/ChronixDB/chronix.ingester/ingester (from $GOPATH)
handler.go:8:2: cannot find package "github.com/gogo/protobuf/proto" in any of:
        /usr/local/go/src/github.com/gogo/protobuf/proto (from $GOROOT)
        /home/ubuntu/chronix/chronix-ingester/src/github.com/gogo/protobuf/proto (from $GOPATH)
handler.go:9:2: cannot find package "github.com/golang/snappy" in any of:
        /usr/local/go/src/github.com/golang/snappy (from $GOROOT)
        /home/ubuntu/chronix/chronix-ingester/src/github.com/golang/snappy (from $GOPATH)
main.go:14:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
        /usr/local/go/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
        /home/ubuntu/chronix/chronix-ingester/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
handler.go:10:2: cannot find package "github.com/prometheus/common/log" in any of:
        /usr/local/go/src/github.com/prometheus/common/log (from $GOROOT)
        /home/ubuntu/chronix/chronix-ingester/src/github.com/prometheus/common/log (from $GOPATH)
handler.go:11:2: cannot find package "github.com/prometheus/common/model" in any of:
        /usr/local/go/src/github.com/prometheus/common/model (from $GOROOT)
        /home/ubuntu/chronix/chronix-ingester/src/github.com/prometheus/common/model (from $GOPATH)
handler.go:12:2: cannot find package "github.com/prometheus/prometheus/storage" in any of:
        /usr/local/go/src/github.com/prometheus/prometheus/storage (from $GOROOT)
        /home/ubuntu/chronix/chronix-ingester/src/github.com/prometheus/prometheus/storage (from $GOPATH)
store.go:9:2: cannot find package "github.com/prometheus/prometheus/storage/local/chunk" in any of:
        /usr/local/go/src/github.com/prometheus/prometheus/storage/local/chunk (from $GOROOT)
        /home/ubuntu/chronix/chronix-ingester/src/github.com/prometheus/prometheus/storage/local/chunk (from $GOPATH)
handler.go:13:2: cannot find package "github.com/prometheus/prometheus/storage/remote" in any of:
        /usr/local/go/src/github.com/prometheus/prometheus/storage/remote (from $GOROOT)
        /home/ubuntu/chronix/chronix-ingester/src/github.com/prometheus/prometheus/storage/remote (from $GOPATH)

any idea what went wrong

**Comment by juliusv** [comment]
Hi, to build Go code, you need to check out and build the packages from `$GOPATH/src/<package name>`. In this case, you need to check out this repo to `$GOPATH/src/github.com/ChronixDB/chronix.ingester`. This is the same issue as https://github.com/ChronixDB/chronix.ingester/issues/6. See also https://golang.org/doc/code.html#Organization

**Comment by Niranjs** [comment]
thanks for your support. Will try it.
