### ISSUE TITLE
How to ingest data from a python client code?

### ISSUE THREAD

**Issue by yusong0926** [ChronixDB/chronix.ingester#8]

**Comment by FlorianLautenschlager** [comment]
Hi, i assume that you want to write data via python to the chronix ingester. Currently the chronix ingester speaks the prometheus protocol. Therefore you have to serialize the data in that format (https://github.com/prometheus/prometheus/blob/master/storage/remote/remote.proto).

**Comment by yusong0926** [comment]
so I have to send data to prometheus first and then collect data from prometheus using chronix ingestor?

**Comment by FlorianLautenschlager** [comment]
No. I thought you want to use the chronix ingester (i collects single metrics, batches them up and writes batches to Chronix). You can of course send data directly to chronix using the native chronix format (currently only java) or use one of the supported protocols: OpenTSDB, Graphite, KairosDB or InfluxDB.

**Comment by yusong0926** [comment]
I couldn't find the API or examples for sending data to chronix server. Would you mind to send me the link?

**Comment by FlorianLautenschlager** [comment]
You can take a look at https://chronix.gitbooks.io/chronix/content/http-api.html (well the documentation is ... at the moment) or at this issue: https://github.com/ChronixDB/chronix.server/issues/129

**Comment by juliusv** [comment]
Closing this as I assume the question has been answered. Please reopen if not.
